---
swagger: '2.0'

securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header

info:
  description: Documentation for Note Service
  version: 1.0.0
  title: Note Service
  contact:
    email: ogunbayo.abayo@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

host: localhost:3201
basePath: /api

tags:
- name: User
  description: List of endpoints for users
- name: Note
  description: List of endpoints for notes

schemes:
- http
- https

paths:
  /auth/signup:
    post:
      tags:
      - User
      summary: Create new user account
      description: ''
      operationId: signupUser
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: User object that is required for store
        required: true
        schema:
          "$ref": "#/definitions/Signup"
      responses:
        '200':
          status: OK
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /auth/login:
    post:
      tags:
      - User
      summary: Authenticate user
      description: ''
      operationId: authenticateUser
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: User object that is required for store
        required: true
        schema:
          "$ref": "#/definitions/Login"
      responses:
        '200':
          status: OK
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /notes:
    post:
      security:
        - bearerAuth: []
      tags:
      - Note
      summary: Create user note
      description: ''
      operationId: createUserNote
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Note object that is required for store
        required: true
        schema:
          "$ref": "#/definitions/Note"
      responses:
        '200':
          status: OK
        '400':
          description: Bad request
        '500':
          description: Internal server error
    get:
      security:
        - bearerAuth: []
      tags:
      - Note
      summary: Fetch all user notes
      description: ''
      operationId: fetchUserNotes
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        '200':
          status: success
        '400':
          description: Invalid input
  /notes/{id}:
    get:
      security:
        - bearerAuth: []
      tags:
      - Note
      summary: Get user note
      description: ''
      operationId: getUserNote
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        description: The note id
        required: true
        schema:
          type: string
          minimum: 1
      responses:
        '200':
          status: success
        '400':
          description: Invalid input
    put:
      security:
        - bearerAuth: []
      tags:
      - Note
      summary: Update user note
      description: ''
      operationId: updateUserNote
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        description: The note id
        required: true
        schema:
          type: string
          minimum: 1
      - in: body
        name: body
        description: Note object that is required for store
        required: true
        schema:
          "$ref": "#/definitions/Note"
      responses:
        '200':
          status: success
        '400':
          description: Invalid input
    delete:
      security:
        - bearerAuth: []
      tags:
      - Note
      summary: Delete user note
      description: ''
      operationId: deleteUserNote
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        description: The note id
        required: true
        schema:
          type: string
          minimum: 1
      responses:
        '200':
          status: success
        '400':
          description: Invalid input
  /notes/{id}/share:
    post:
      security:
        - bearerAuth: []
      tags:
      - Note
      summary: Share user note
      description: ''
      operationId: shareUserNote
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        description: The note id
        required: true
        schema:
          type: string
          minimum: 1
      - in: body
        name: body
        description: Note object that is required for store
        required: true
        schema:
          "$ref": "#/definitions/ShareNote"
      responses:
        '200':
          status: success
        '400':
          description: Invalid input
  /search:
    get:
      security:
        - bearerAuth: []
      tags:
      - Note
      summary: Search notes
      description: ''
      operationId: searchNotes
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: query
        name: q
        description: The search keyword
        schema:
          type: string
          minimum: 1
      responses:
        '200':
          status: success

definitions:
  Signup:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      password:
        type: string

  Login:
    type: object
    properties:
      email:
        type: string
      password:
        type: string

  Note:
    type: object
    properties:
      title:
        type: string
      content:
        type: string

  ShareNote:
    type: object
    properties:
      email:
        type: string
